versions:
  "17.18.03":
    token: "17183"
    ova_url: "http://10.76.90.102/cat9kv-universalk9_serial.17.18.03.ova"
    iso_url: "http://10.76.90.102/cat9kv-universalk9_serial.17.18.03.iso"
    deployment_method: ova
    ova_keep_hardware_defaults: true
    serial_base: 8021
    serial_step: 10
